export const JokeActionType = {
  SET_JOKE_OF_THE_DAY: "SET_JOKE_OF_THE_DAY",
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_CATEGORY_DATA: "SET_CATEGORY_DATA",
  SET_SELECTED_CATEGORY: "SET_SELECTED_CATEGORY",
  SET_SEARCHED_JOKE:"SET_SEARCHED_JOKE",
  SET_SEARCH_DATA:"SET_SEARCHED_DATA",
  SET_VALIDATION_ERROR:'SET_VALIDATION_ERROR'
};
