export const JokeActionType = {
  SET_JOKE_OF_THE_DAY: "SET_JOKE_OF_THE_DAY",
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_CATEGORY_DATA: "SET_CATEGORY_DATA",
  SET_SELECTED_CATEGORY: "SET_SELECTED_CATEGORY",
  SET_SEARCHED_JOKE:"SET_SEARCHED_JOKE"
};
